// <auto-generated />
using System;
using Escalator.API;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace EscalatorclassAPIEscalator.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20201122061921_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Escalator.Common.Models.Escalation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Account")
                        .HasColumnType("text");

                    b.Property<long>("AssignedAgent")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CloseDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("CompletedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DueBy")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("JurisdictionId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("OpenDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("details")
                        .HasColumnType("text");

                    b.Property<string>("emailAddress")
                        .HasColumnType("text");

                    b.Property<string>("phoneNumber")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Escalations");
                });
#pragma warning restore 612, 618
        }
    }
}
